[package]
name = "CCBPlusTree"
version = "0.0.64"
edition = "2021"
authors = ["Amir El-Shaikh <elshaikh@mathematik.uni-marburg.de>"]
description = "Experimental Concurrency Control CRUD B+Tree Implementation"
repository = "https://github.com/umr-dbs/CC-BPlusTree"

[profile.dev]
overflow-checks = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
rand = "0.8.5"
num_cpus = "1.15.0"
itertools = "0.10.5"
parking_lot = "0.12.1"
serde = { version ="1.0.152", features = ["derive", "rc"] }
serde_json = { version = "1.0.93" }
[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.139"