[package]
name = "CCBPlusTree"
version = "0.0.37"
edition = "2021"
authors = ["Amir El-Shaikh <elshaikh@mathematik.uni-marburg.de>"]
description = "Experimental Concurrency Control B+Tree single versioned and versioned via version lists Implementation"
repository = "https://github.com/umr-dbs/CC-BPlusTree"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ChronicleDB = { path = "../ChronicleDB", version = "1.0.51" }
MVCCBPlusTree = { path = "../MVCC-BPlusTree", version = "0.0.65" }
chrono = "0.4.23"
rand = "0.8.5"
num_cpus = "1.14"
itertools = "0.10.5"
parking_lot = "0.12.1"
serde = { version ="1.0.14", features = ["derive", "rc"] }
serde_json = { version = "1.0.8" }
[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.137"