[package]
name = "CCBPlusTree"
version = "0.0.50"
edition = "2021"
authors = ["Amir El-Shaikh <elshaikh@mathematik.uni-marburg.de>"]
description = "Experimental Concurrency Control B+Tree single versioned and versioned via version lists Implementation"
repository = "https://github.com/umr-dbs/CC-BPlusTree"

[profile.dev]
overflow-checks = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
TXDataModel = { path = "../TXDataModel", version = "0.1.7" }
chrono = "0.4.23"
rand = "0.8.5"
num_cpus = "1.15"
itertools = "0.10.5"
parking_lot = "0.12.1"
serde = { version ="1.0.152", features = ["derive", "rc"] }
serde_json = { version = "1.0.91" }